
package com.edmundophie.adapter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SixAdapter", targetNamespace = "http://adapter.edmundophie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SixAdapter {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassParticipants", targetNamespace = "http://adapter.edmundophie.com/", className = "com.edmundophie.adapter.GetClassParticipants")
    @ResponseWrapper(localName = "getClassParticipantsResponse", targetNamespace = "http://adapter.edmundophie.com/", className = "com.edmundophie.adapter.GetClassParticipantsResponse")
    @Action(input = "http://adapter.edmundophie.com/SixAdapter/getClassParticipantsRequest", output = "http://adapter.edmundophie.com/SixAdapter/getClassParticipantsResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://adapter.edmundophie.com/SixAdapter/getClassParticipants/Fault/IOException")
    })
    public String getClassParticipants(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws IOException_Exception
    ;

}
