
package com.edmundophie.adapter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SixAdapterService", targetNamespace = "http://adapter.edmundophie.com/", wsdlLocation = "http://edmunds-macbook-pro.local:8080/six_adapter_war_exploded/SixAdapterService?wsdl")
public class SixAdapterService
    extends Service
{

    private final static URL SIXADAPTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIXADAPTERSERVICE_EXCEPTION;
    private final static QName SIXADAPTERSERVICE_QNAME = new QName("http://adapter.edmundophie.com/", "SixAdapterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://edmunds-macbook-pro.local:8080/six_adapter_war_exploded/SixAdapterService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIXADAPTERSERVICE_WSDL_LOCATION = url;
        SIXADAPTERSERVICE_EXCEPTION = e;
    }

    public SixAdapterService() {
        super(__getWsdlLocation(), SIXADAPTERSERVICE_QNAME);
    }

    public SixAdapterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIXADAPTERSERVICE_QNAME, features);
    }

    public SixAdapterService(URL wsdlLocation) {
        super(wsdlLocation, SIXADAPTERSERVICE_QNAME);
    }

    public SixAdapterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIXADAPTERSERVICE_QNAME, features);
    }

    public SixAdapterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SixAdapterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SixAdapter
     */
    @WebEndpoint(name = "SixAdapterPort")
    public SixAdapter getSixAdapterPort() {
        return super.getPort(new QName("http://adapter.edmundophie.com/", "SixAdapterPort"), SixAdapter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SixAdapter
     */
    @WebEndpoint(name = "SixAdapterPort")
    public SixAdapter getSixAdapterPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://adapter.edmundophie.com/", "SixAdapterPort"), SixAdapter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIXADAPTERSERVICE_EXCEPTION!= null) {
            throw SIXADAPTERSERVICE_EXCEPTION;
        }
        return SIXADAPTERSERVICE_WSDL_LOCATION;
    }

}
